-- EDM module UAT test data (odb database): the "UAT" list with 40 test contacts whose
-- custom fields cover every Audience Builder filter (spec 6). Run after edm_seed.sql.
-- Skipped when the list / an address on it already exists, so it is safe to run again.
--
-- Addresses are the Amazon SES mailbox simulator (success+uatNN@simulator.amazonses.com):
-- SES accepts them, they never bounce and do not count against sending reputation,
-- and they work in the SES sandbox. Do not load this file on production.
-- Relative dates (birthdays, last purchase) were generated on 2026-10-01.

SET NAMES utf8mb4;
SET @now = NOW();

INSERT INTO `edm_lists` (`name`, `description`, `is_active`, `created_by_name`, `created_at`, `updated_at`)
SELECT 'UAT', 'Test contacts on the SES mailbox simulator (edm_seed_uat.sql).', 1, 'System', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_lists` WHERE `name` = 'UAT' AND `deleted_at` IS NULL);
SET @uat = (SELECT `id` FROM `edm_lists` WHERE `name` = 'UAT' AND `deleted_at` IS NULL ORDER BY `id` LIMIT 1);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00001', 'success+uat01@simulator.amazonses.com', 'Muhammad Nair', '{"city": "Taiping", "race": "Others", "lofra": "Loyal", "state": "Perak", "gender": "F", "mobile": "0100000002", "dormant": "0", "birthday": "1956-05-04", "rfm_score": "13", "nationality": "Malaysian", "rfm_segment": "Loyal", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1001", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-02-24", "product_brand": "Blackmores", "nearest_outlet": "Alpro Petaling Jaya", "points_balance": "1680", "total_spending": "3840.89", "member_category": "Personal", "membership_type": "Gold", "engagement_score": "80", "product_category": "Baby Care, Supplements", "last_visit_outlet": "Alpro Petaling Jaya", "last_purchase_date": "2026-09-19", "preferred_language": "English", "purchase_frequency": "15", "client_interest_group": "Baby and mother care", "client_sales_category": "Online"}', 'uat-seed', 1, '2026-09-22 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat01@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00002', 'success+uat02@simulator.amazonses.com', 'Nurul Ismail', '{"city": "Melaka", "race": "Bumiputera Sabah", "lofra": "Hopper", "state": "Melaka", "gender": "M", "mobile": "0100000003", "dormant": "0", "birthday": "1979-01-07", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Johor Bahru", "voucher_code": "UAT-1002", "create_outlet": "Alpro Johor Bahru", "points_expiry": "2027-08-03", "product_brand": "Panadol", "nearest_outlet": "Alpro Cheras", "points_balance": "330", "total_spending": "345.91", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "15", "product_category": "Beauty, Medical Devices", "last_visit_outlet": "Alpro Cheras", "last_purchase_date": "2025-10-17", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "3", "client_interest_group": "Beauty and skincare", "client_sales_category": "Retail"}', 'uat-seed', 1, '2025-08-10 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat02@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00003', 'success+uat03@simulator.amazonses.com', 'Li Na Abdullah', '{"city": "Klang", "race": "Chinese", "lofra": "Hopper", "state": "Selangor", "gender": "F", "mobile": "0100000004", "dormant": "0", "birthday": "1987-12-17", "rfm_score": "5", "nationality": "Malaysian", "rfm_segment": "At Risk", "group_outlet": "Alpro Klang", "voucher_code": "UAT-1003", "create_outlet": "Alpro Klang", "points_expiry": "2027-08-11", "product_brand": "Nature''s Way", "nearest_outlet": "Alpro Shah Alam", "points_balance": "442", "total_spending": "1534.75", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "26", "product_category": "Baby Care, Beauty", "last_visit_outlet": "Alpro Shah Alam", "last_purchase_date": "2026-02-09", "preferred_language": "Chinese", "purchase_frequency": "5", "client_interest_group": "Elderly care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-02-19 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat03@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00004', 'success+uat04@simulator.amazonses.com', 'Kevin Ismail', '{"city": "Klang", "race": "Bumiputera Sabah", "lofra": "Average", "state": "Selangor", "gender": "F", "mobile": "0100000005", "dormant": "0", "birthday": "2002-07-13", "rfm_score": "6", "nationality": "Malaysian", "rfm_segment": "New", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1004", "create_outlet": "Alpro Cheras", "points_expiry": "2027-07-30", "product_brand": "Vitahealth", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "882", "total_spending": "630.01", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "42", "product_category": "Beauty, Baby Care", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-06-02", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "6", "client_interest_group": "Fitness", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-04-19 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat04@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00005', 'success+uat05@simulator.amazonses.com', 'Jun Hao Abdullah', '{"city": "Ipoh", "race": "Malay", "lofra": "Loyal", "state": "Perak", "gender": "M", "mobile": "0100000006", "dormant": "0", "birthday": "1999-12-28", "rfm_score": "13", "nationality": "Malaysian", "rfm_segment": "Loyal", "group_outlet": "Alpro Online", "voucher_code": "UAT-1005", "create_outlet": "Alpro Online", "points_expiry": "2027-04-07", "product_brand": "Omron", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "1162", "total_spending": "3154.61", "member_category": "Personal", "membership_type": "Gold", "engagement_score": "83", "product_category": "Supplements", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-09-19", "preferred_language": "English", "purchase_frequency": "15", "client_interest_group": "Chronic care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-04-06 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat05@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00006', 'success+uat06@simulator.amazonses.com', 'Nurul Lee', '{"city": "Melaka", "race": "Malay", "lofra": "Average", "state": "Melaka", "gender": "F", "mobile": "0100000007", "dormant": "0", "birthday": "1989-12-25", "rfm_score": "7", "nationality": "Singaporean", "rfm_segment": "New", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1006", "create_outlet": "Alpro Kuching", "points_expiry": "2026-12-25", "product_brand": "Cetaphil", "nearest_outlet": "Alpro Johor Bahru", "points_balance": "420", "total_spending": "924.32", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "42", "product_category": "Medicine, Baby Care", "last_visit_outlet": "Alpro Johor Bahru", "last_purchase_date": "2026-07-04", "preferred_language": "English", "purchase_frequency": "5", "client_interest_group": "Health supplements", "client_sales_category": "Online"}', 'uat-seed', 1, '2026-08-12 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat06@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00007', 'success+uat07@simulator.amazonses.com', 'Jun Hao Subramaniam', '{"city": "Butterworth", "race": "Bumiputera Sarawak", "lofra": "Loyal", "state": "Pulau Pinang", "gender": "M", "mobile": "0100000008", "dormant": "0", "birthday": "1956-04-23", "rfm_score": "14", "nationality": "Indonesian", "rfm_segment": "VIP", "group_outlet": "Alpro Klang", "voucher_code": "UAT-1007", "create_outlet": "Alpro Klang", "points_expiry": "2027-09-12", "product_brand": "Blackmores", "nearest_outlet": "Alpro Ipoh", "points_balance": "1513", "total_spending": "2047.10", "member_category": "Corporate", "membership_type": "Platinum", "engagement_score": "89", "product_category": "Medicine, Medical Devices", "last_visit_outlet": "Alpro Ipoh", "last_purchase_date": "2026-08-22", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "12", "client_interest_group": "Baby and mother care", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-09-18 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat07@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00008', 'success+uat08@simulator.amazonses.com', 'Zara Subramaniam', '{"city": "Petaling Jaya", "race": "Others", "lofra": "Average", "state": "Selangor", "gender": "F", "mobile": "0100000009", "dormant": "0", "birthday": "2002-04-05", "rfm_score": "6", "nationality": "Malaysian", "rfm_segment": "At Risk", "group_outlet": "Alpro Petaling Jaya", "voucher_code": "UAT-1008", "create_outlet": "Alpro Petaling Jaya", "points_expiry": "2027-06-04", "product_brand": "Panadol", "nearest_outlet": "Alpro Ipoh", "points_balance": "420", "total_spending": "1120.78", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "35", "product_category": "Personal Care, Medical Devices", "last_visit_outlet": "Alpro Ipoh", "last_purchase_date": "2026-03-23", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "6", "client_interest_group": "Beauty and skincare", "client_sales_category": "Retail"}', 'uat-seed', 1, '2026-09-27 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat08@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00009', 'success+uat09@simulator.amazonses.com', 'Kevin Rahman', '{"city": "Kota Kinabalu", "race": "Bumiputera Sarawak", "lofra": "Average", "state": "Sabah", "gender": "M", "mobile": "0100000010", "dormant": "0", "birthday": "1968-12-09", "rfm_score": "8", "nationality": "Singaporean", "rfm_segment": "New", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1009", "create_outlet": "Alpro Cheras", "points_expiry": "2027-04-03", "product_brand": "Nature''s Way", "nearest_outlet": "Alpro Ipoh", "points_balance": "920", "total_spending": "2070.58", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "46", "product_category": "Baby Care, Supplements", "last_visit_outlet": "Alpro Ipoh", "last_purchase_date": "2026-08-25", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "5", "client_interest_group": "Elderly care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2025-11-09 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat09@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00010', 'success+uat10@simulator.amazonses.com', 'Priya Wong', '{"city": "Kuching", "race": "Others", "lofra": "Average", "state": "Sarawak", "gender": "F", "mobile": "0100000011", "dormant": "0", "birthday": "1978-07-23", "rfm_score": "8", "nationality": "Others", "rfm_segment": "Potential Loyalist", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1010", "create_outlet": "Alpro Cheras", "points_expiry": "2027-02-22", "product_brand": "Drypers", "nearest_outlet": "Alpro Petaling Jaya", "points_balance": "504", "total_spending": "2688.91", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "56", "product_category": "Baby Care, Supplements", "last_visit_outlet": "Alpro Petaling Jaya", "last_purchase_date": "2026-08-21", "preferred_language": "English", "purchase_frequency": "9", "client_interest_group": "Fitness", "client_sales_category": "Retail"}', 'uat-seed', 1, '2025-05-27 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat10@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00011', 'success+uat11@simulator.amazonses.com', 'Farah Hassan', '{"city": "Ipoh", "race": "Chinese", "lofra": "Loyal", "state": "Perak", "gender": "F", "mobile": "0100000012", "dormant": "0", "birthday": "1986-02-23", "rfm_score": "12", "nationality": "Others", "rfm_segment": "Loyal", "group_outlet": "Alpro Ipoh", "voucher_code": "UAT-1011", "create_outlet": "Alpro Ipoh", "points_expiry": "2027-01-28", "product_brand": "Nature''s Way", "nearest_outlet": "Alpro Online", "points_balance": "1660", "total_spending": "2075.40", "member_category": "Personal", "membership_type": "Gold", "engagement_score": "83", "product_category": "Medical Devices, Baby Care", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2026-08-21", "preferred_language": "English", "purchase_frequency": "11", "client_interest_group": "Chronic care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2025-11-22 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat11@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00012', 'success+uat12@simulator.amazonses.com', 'Rajesh Abdullah', '{"city": "Muar", "race": "Bumiputera Sarawak", "lofra": "Average", "state": "Johor", "gender": "F", "mobile": "0100000013", "dormant": "0", "birthday": "1973-12-27", "rfm_score": "5", "nationality": "Malaysian", "rfm_segment": "New", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1012", "create_outlet": "Alpro Kuching", "points_expiry": "2027-03-18", "product_brand": "Panadol", "nearest_outlet": "Alpro Petaling Jaya", "points_balance": "410", "total_spending": "2173.57", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "41", "product_category": "Medicine, Personal Care", "last_visit_outlet": "Alpro Petaling Jaya", "last_purchase_date": "2026-05-09", "preferred_language": "English", "purchase_frequency": "4", "client_interest_group": "Health supplements", "client_sales_category": "Online"}', 'uat-seed', 1, '2026-01-11 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat12@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00013', 'success+uat13@simulator.amazonses.com', 'Jun Hao Tan', '{"city": "Sungai Petani", "race": "Bumiputera Sabah", "lofra": "Loyal", "state": "Kedah", "gender": "M", "mobile": "0100000014", "dormant": "0", "birthday": "1987-01-26", "rfm_score": "12", "nationality": "Malaysian", "rfm_segment": "Loyal", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1013", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-07-09", "product_brand": "Cetaphil", "nearest_outlet": "Alpro Online", "points_balance": "1328", "total_spending": "2158.36", "member_category": "Personal", "membership_type": "Gold", "engagement_score": "83", "product_category": "Supplements, Baby Care", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2026-09-05", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "15", "client_interest_group": "Baby and mother care", "client_sales_category": "Retail"}', 'uat-seed', 1, '2026-04-16 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat13@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00014', 'success+uat14@simulator.amazonses.com', 'Siti Lim', '{"city": "Sandakan", "race": "Bumiputera Sarawak", "lofra": "Average", "state": "Sabah", "gender": "M", "mobile": "0100000015", "dormant": "0", "birthday": "1970-03-21", "rfm_score": "7", "nationality": "Others", "rfm_segment": "At Risk", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1014", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-07-18", "product_brand": "Omron", "nearest_outlet": "Alpro Online", "points_balance": "570", "total_spending": "2166.98", "member_category": "Corporate", "membership_type": "Standard", "engagement_score": "38", "product_category": "Beauty, Medicine", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2025-11-16", "preferred_language": "English", "purchase_frequency": "8", "client_interest_group": "Beauty and skincare", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-08-03 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat14@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00015', 'success+uat15@simulator.amazonses.com', 'Daniel Abdullah', '{"city": "Kuching", "race": "Bumiputera Sarawak", "lofra": "Average", "state": "Sarawak", "gender": "F", "mobile": "0100000016", "dormant": "0", "birthday": "2001-12-08", "rfm_score": "5", "nationality": "Malaysian", "rfm_segment": "At Risk", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1015", "create_outlet": "Alpro Cheras", "points_expiry": "2027-09-06", "product_brand": "Blackmores", "nearest_outlet": "Alpro Cheras", "points_balance": "240", "total_spending": "1620.45", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "30", "product_category": "Personal Care", "last_visit_outlet": "Alpro Cheras", "last_purchase_date": "2026-01-01", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "7", "client_interest_group": "Elderly care", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-06-16 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat15@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00016', 'success+uat16@simulator.amazonses.com', 'Hafiz Ismail', '{"city": "Shah Alam", "race": "Indian", "lofra": "Hopper", "state": "Selangor", "gender": "M", "mobile": "0100000017", "dormant": "0", "birthday": "1962-10-10", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Online", "voucher_code": "UAT-1016", "create_outlet": "Alpro Online", "points_expiry": "2026-10-22", "product_brand": "Vitahealth", "nearest_outlet": "Alpro Shah Alam", "points_balance": "288", "total_spending": "288.54", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "12", "product_category": "Supplements, Beauty", "last_visit_outlet": "Alpro Shah Alam", "last_purchase_date": "2025-11-21", "preferred_language": "Tamil", "purchase_frequency": "0", "client_interest_group": "Fitness", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-04-30 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat16@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00017', 'success+uat17@simulator.amazonses.com', 'Nurul Nair', '{"city": "Alor Setar", "race": "Bumiputera Sarawak", "lofra": "Average", "state": "Kedah", "gender": "F", "mobile": "0100000018", "dormant": "0", "birthday": "2006-12-03", "rfm_score": "8", "nationality": "Indonesian", "rfm_segment": "New", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1017", "create_outlet": "Alpro Cheras", "points_expiry": "2027-08-26", "product_brand": "Blackmores", "nearest_outlet": "Alpro Johor Bahru", "points_balance": "966", "total_spending": "1050.05", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "42", "product_category": "Medical Devices, Personal Care", "last_visit_outlet": "Alpro Johor Bahru", "last_purchase_date": "2026-04-24", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "9", "client_interest_group": "Chronic care", "client_sales_category": "Staff"}', 'uat-seed', 1, '2026-09-14 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat17@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00018', 'success+uat18@simulator.amazonses.com', 'Arjun Tan', '{"city": "Kuantan", "race": "Malay", "lofra": "Risk", "state": "Pahang", "gender": "F", "mobile": "0100000019", "dormant": "1", "birthday": "2001-12-14", "rfm_score": "7", "nationality": "Indonesian", "rfm_segment": "Dormant", "group_outlet": "Alpro Petaling Jaya", "voucher_code": "UAT-1018", "create_outlet": "Alpro Petaling Jaya", "points_expiry": "2027-05-10", "product_brand": "Omron", "nearest_outlet": "Alpro Shah Alam", "points_balance": "504", "total_spending": "576.43", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "36", "product_category": "Supplements, Medical Devices", "last_visit_outlet": "Alpro Shah Alam", "last_purchase_date": "2025-08-10", "preferred_language": "English", "purchase_frequency": "6", "client_interest_group": "Health supplements", "client_sales_category": "Retail"}', 'uat-seed', 1, '2026-06-16 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat18@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00019', 'success+uat19@simulator.amazonses.com', 'Farah Wong', '{"city": "Alor Setar", "race": "Chinese", "lofra": "Average", "state": "Kedah", "gender": "F", "mobile": "0100000020", "dormant": "0", "birthday": "1987-11-04", "rfm_score": "9", "nationality": "Others", "rfm_segment": "Potential Loyalist", "group_outlet": "Alpro Klang", "voucher_code": "UAT-1019", "create_outlet": "Alpro Klang", "points_expiry": "2026-11-23", "product_brand": "Panadol", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "1564", "total_spending": "1768.78", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "68", "product_category": "Medical Devices, Baby Care", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-05-10", "preferred_language": "English", "purchase_frequency": "12", "client_interest_group": "Baby and mother care", "client_sales_category": "Staff"}', 'uat-seed', 1, '2026-01-09 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat19@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00020', 'success+uat20@simulator.amazonses.com', 'Siti Ismail', '{"city": "Petaling Jaya", "race": "Bumiputera Sarawak", "lofra": "Risk", "state": "Selangor", "gender": "F", "mobile": "0100000021", "dormant": "1", "birthday": "1981-01-18", "rfm_score": "6", "nationality": "Indonesian", "rfm_segment": "Dormant", "group_outlet": "Alpro George Town", "voucher_code": "UAT-1020", "create_outlet": "Alpro George Town", "points_expiry": "2027-09-04", "product_brand": "Drypers", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "900", "total_spending": "1116.52", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "36", "product_category": "Baby Care, Beauty", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2025-03-15", "preferred_language": "English", "purchase_frequency": "6", "client_interest_group": "Beauty and skincare", "client_sales_category": "Staff"}', 'uat-seed', 1, '2025-03-14 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat20@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00021', 'success+uat21@simulator.amazonses.com', 'Hafiz Rahman', '{"city": "Batu Pahat", "race": "Bumiputera Sabah", "lofra": "Average", "state": "Johor", "gender": "M", "mobile": "0100000022", "dormant": "0", "birthday": "1973-12-02", "rfm_score": "11", "nationality": "Malaysian", "rfm_segment": "Loyal", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1021", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-08-08", "product_brand": "Nature''s Way", "nearest_outlet": "Alpro Klang", "points_balance": "1120", "total_spending": "4060.72", "member_category": "Corporate", "membership_type": "Gold", "engagement_score": "70", "product_category": "Baby Care", "last_visit_outlet": "Alpro Klang", "last_purchase_date": "2026-09-12", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "10", "client_interest_group": "Elderly care", "client_sales_category": "Online"}', 'uat-seed', 1, '2026-05-12 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat21@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00022', 'success+uat22@simulator.amazonses.com', 'Rajesh Wong', '{"city": "Kuantan", "race": "Malay", "lofra": "Loyal", "state": "Pahang", "gender": "M", "mobile": "0100000023", "dormant": "0", "birthday": "1958-03-11", "rfm_score": "14", "nationality": "Others", "rfm_segment": "VIP", "group_outlet": "Alpro Johor Bahru", "voucher_code": "UAT-1022", "create_outlet": "Alpro Johor Bahru", "points_expiry": "2027-06-01", "product_brand": "Omron", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "1674", "total_spending": "4464.57", "member_category": "Personal", "membership_type": "Platinum", "engagement_score": "93", "product_category": "Baby Care, Beauty", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-09-06", "preferred_language": "English", "purchase_frequency": "17", "client_interest_group": "Fitness", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-08-18 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat22@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00023', 'success+uat23@simulator.amazonses.com', 'Kumar Abdullah', '{"city": "Melaka", "race": "Chinese", "lofra": "Risk", "state": "Melaka", "gender": "F", "mobile": "0100000024", "dormant": "1", "birthday": "1956-12-28", "rfm_score": "6", "nationality": "Others", "rfm_segment": "Dormant", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1023", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-07-05", "product_brand": "Vitahealth", "nearest_outlet": "Alpro Online", "points_balance": "300", "total_spending": "1350.71", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "30", "product_category": "Supplements, Medicine", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2025-04-04", "preferred_language": "Chinese", "purchase_frequency": "7", "client_interest_group": "Chronic care", "client_sales_category": "Staff"}', 'uat-seed', 1, '2026-06-03 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat23@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00024', 'success+uat24@simulator.amazonses.com', 'Li Na Abdullah', '{"city": "Kota Kinabalu", "race": "Bumiputera Sarawak", "lofra": "Hopper", "state": "Sabah", "gender": "M", "mobile": "0100000025", "dormant": "0", "birthday": "1957-12-11", "rfm_score": "4", "nationality": "Singaporean", "rfm_segment": "At Risk", "group_outlet": "Alpro Klang", "voucher_code": "UAT-1024", "create_outlet": "Alpro Klang", "points_expiry": "2027-05-19", "product_brand": "Cetaphil", "nearest_outlet": "Alpro Kuching", "points_balance": "696", "total_spending": "1218.78", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "29", "product_category": "Medicine, Beauty", "last_visit_outlet": "Alpro Kuching", "last_purchase_date": "2025-12-11", "preferred_language": "English", "purchase_frequency": "2", "client_interest_group": "Health supplements", "client_sales_category": "Staff"}', 'uat-seed', 1, '2025-06-14 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat24@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00025', 'success+uat25@simulator.amazonses.com', 'Priya Lim', '{"city": "Subang Jaya", "race": "Indian", "lofra": "Average", "state": "Selangor", "gender": "F", "mobile": "0100000026", "dormant": "0", "birthday": "1955-11-05", "rfm_score": "5", "nationality": "Malaysian", "rfm_segment": "At Risk", "group_outlet": "Alpro Online", "voucher_code": "UAT-1025", "create_outlet": "Alpro Online", "points_expiry": "2027-02-01", "product_brand": "Blackmores", "nearest_outlet": "Alpro Petaling Jaya", "points_balance": "777", "total_spending": "1517.29", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "37", "product_category": "Medical Devices, Medicine", "last_visit_outlet": "Alpro Petaling Jaya", "last_purchase_date": "2025-11-27", "preferred_language": "Tamil", "purchase_frequency": "6", "client_interest_group": "Baby and mother care", "client_sales_category": "Retail"}', 'uat-seed', 1, '2025-09-22 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat25@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00026', 'success+uat26@simulator.amazonses.com', 'Kevin Subramaniam', '{"city": "Shah Alam", "race": "Bumiputera Sarawak", "lofra": "Risk", "state": "Selangor", "gender": "F", "mobile": "0100000027", "dormant": "1", "birthday": "1984-02-09", "rfm_score": "5", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Klang", "voucher_code": "UAT-1026", "create_outlet": "Alpro Klang", "points_expiry": "2027-06-27", "product_brand": "Bio-Life", "nearest_outlet": "Alpro Online", "points_balance": "725", "total_spending": "435.55", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "29", "product_category": "Beauty, Baby Care", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2025-07-13", "preferred_language": "English", "purchase_frequency": "5", "client_interest_group": "Beauty and skincare", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-08-25 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat26@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00027', 'success+uat27@simulator.amazonses.com', 'Nurul Hassan', '{"city": "Melaka", "race": "Malay", "lofra": "Average", "state": "Melaka", "gender": "M", "mobile": "0100000028", "dormant": "0", "birthday": "1988-12-04", "rfm_score": "7", "nationality": "Singaporean", "rfm_segment": "At Risk", "group_outlet": "Alpro Online", "voucher_code": "UAT-1027", "create_outlet": "Alpro Online", "points_expiry": "2026-12-09", "product_brand": "Blackmores", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "740", "total_spending": "1258.42", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "37", "product_category": "Personal Care, Beauty", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-04-04", "preferred_language": "English", "purchase_frequency": "8", "client_interest_group": "Elderly care", "client_sales_category": "Retail"}', 'uat-seed', 1, '2025-02-05 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat27@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00028', 'success+uat28@simulator.amazonses.com', 'Kumar Nair', '{"city": "Kuala Lumpur", "race": "Malay", "lofra": "Loyal", "state": "W.P. Kuala Lumpur", "gender": "F", "mobile": "0100000029", "dormant": "0", "birthday": "1976-05-17", "rfm_score": "13", "nationality": "Malaysian", "rfm_segment": "Loyal", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1028", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-02-04", "product_brand": "Panadol", "nearest_outlet": "Alpro George Town", "points_balance": "1680", "total_spending": "3024.04", "member_category": "Corporate", "membership_type": "Gold", "engagement_score": "84", "product_category": "Personal Care, Medicine", "last_visit_outlet": "Alpro George Town", "last_purchase_date": "2026-08-30", "preferred_language": "English", "purchase_frequency": "14", "client_interest_group": "Fitness", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-05-02 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat28@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00029', 'success+uat29@simulator.amazonses.com', 'Mei Yee Hassan', '{"city": "Melaka", "race": "Chinese", "lofra": "Average", "state": "Melaka", "gender": "M", "mobile": "0100000030", "dormant": "0", "birthday": "1975-11-02", "rfm_score": "11", "nationality": "Malaysian", "rfm_segment": "Potential Loyalist", "group_outlet": "Alpro Cheras", "voucher_code": "UAT-1029", "create_outlet": "Alpro Cheras", "points_expiry": "2027-08-10", "product_brand": "Bio-Life", "nearest_outlet": "Alpro Online", "points_balance": "1632", "total_spending": "3672.79", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "68", "product_category": "Baby Care, Personal Care", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2026-07-30", "preferred_language": "English", "purchase_frequency": "12", "client_interest_group": "Chronic care", "client_sales_category": "Online"}', 'uat-seed', 1, '2026-07-28 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat29@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00030', 'success+uat30@simulator.amazonses.com', 'Kevin Tan', '{"city": "Miri", "race": "Indian", "lofra": "Risk", "state": "Sarawak", "gender": "M", "mobile": "0100000031", "dormant": "1", "birthday": "1965-12-28", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Shah Alam", "voucher_code": "UAT-1030", "create_outlet": "Alpro Shah Alam", "points_expiry": "2027-04-18", "product_brand": "Vitahealth", "nearest_outlet": "Alpro Klang", "points_balance": "45", "total_spending": "105.05", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "5", "product_category": "Beauty, Supplements", "last_visit_outlet": "Alpro Klang", "last_purchase_date": "2025-02-23", "preferred_language": "Tamil", "purchase_frequency": "1", "client_interest_group": "Health supplements", "client_sales_category": "Staff"}', 'uat-seed', 1, '2025-04-04 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat30@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00031', 'success+uat31@simulator.amazonses.com', 'Kevin Nair', '{"city": "Cheras", "race": "Chinese", "lofra": "Hopper", "state": "W.P. Kuala Lumpur", "gender": "F", "mobile": "0100000032", "dormant": "0", "birthday": "1966-12-05", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1031", "create_outlet": "Alpro Kuching", "points_expiry": "2027-03-20", "product_brand": "Vitahealth", "nearest_outlet": "Alpro Klang", "points_balance": "104", "total_spending": "429.52", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "13", "product_category": "Medical Devices, Personal Care", "last_visit_outlet": "Alpro Klang", "last_purchase_date": "2026-03-29", "preferred_language": "English", "purchase_frequency": "1", "client_interest_group": "Baby and mother care", "client_sales_category": "Retail"}', 'uat-seed', 1, '2026-09-12 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat31@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00032', 'success+uat32@simulator.amazonses.com', 'Amirah Rahman', '{"city": "Petaling Jaya", "race": "Malay", "lofra": "Average", "state": "Selangor", "gender": "M", "mobile": "0100000033", "dormant": "0", "birthday": "1999-10-08", "rfm_score": "9", "nationality": "Malaysian", "rfm_segment": "New", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1032", "create_outlet": "Alpro Kuching", "points_expiry": "2027-09-11", "product_brand": "Blackmores", "nearest_outlet": "Alpro Shah Alam", "points_balance": "1000", "total_spending": "2000.13", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "50", "product_category": "Medicine, Medical Devices", "last_visit_outlet": "Alpro Shah Alam", "last_purchase_date": "2026-07-19", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "7", "client_interest_group": "Beauty and skincare", "client_sales_category": "Online"}', 'uat-seed', 1, '2025-05-02 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat32@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00033', 'success+uat33@simulator.amazonses.com', 'Arjun Subramaniam', '{"city": "Melaka", "race": "Others", "lofra": "Loyal", "state": "Melaka", "gender": "F", "mobile": "0100000034", "dormant": "0", "birthday": "1953-12-06", "rfm_score": "14", "nationality": "Malaysian", "rfm_segment": "VIP", "group_outlet": "Alpro Online", "voucher_code": "UAT-1033", "create_outlet": "Alpro Online", "points_expiry": "2027-06-18", "product_brand": "Omron", "nearest_outlet": "Alpro Shah Alam", "points_balance": "850", "total_spending": "3400.23", "member_category": "Personal", "membership_type": "Platinum", "engagement_score": "85", "product_category": "Medical Devices, Baby Care", "last_visit_outlet": "Alpro Shah Alam", "last_purchase_date": "2026-08-30", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "16", "client_interest_group": "Elderly care", "client_sales_category": "Retail"}', 'uat-seed', 1, '2024-12-24 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat33@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00034', 'success+uat34@simulator.amazonses.com', 'Amirah Ismail', '{"city": "George Town", "race": "Chinese", "lofra": "Loyal", "state": "Pulau Pinang", "gender": "F", "mobile": "0100000035", "dormant": "0", "birthday": "1990-09-03", "rfm_score": "15", "nationality": "Malaysian", "rfm_segment": "VIP", "group_outlet": "Alpro Kota Kinabalu", "voucher_code": "UAT-1034", "create_outlet": "Alpro Kota Kinabalu", "points_expiry": "2027-05-17", "product_brand": "Bio-Life", "nearest_outlet": "Alpro Johor Bahru", "points_balance": "1767", "total_spending": "5580.53", "member_category": "Personal", "membership_type": "Platinum", "engagement_score": "93", "product_category": "Baby Care, Beauty", "last_visit_outlet": "Alpro Johor Bahru", "last_purchase_date": "2026-08-28", "preferred_language": "English", "purchase_frequency": "14", "client_interest_group": "Fitness", "client_sales_category": "Retail"}', 'uat-seed', 1, '2025-02-09 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat34@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00035', 'success+uat35@simulator.amazonses.com', 'Farah Nair', '{"city": "Kota Kinabalu", "race": "Indian", "lofra": "Hopper", "state": "Sabah", "gender": "F", "mobile": "0100000036", "dormant": "0", "birthday": "1984-06-28", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "At Risk", "group_outlet": "Alpro Johor Bahru", "voucher_code": "UAT-1035", "create_outlet": "Alpro Johor Bahru", "points_expiry": "2027-02-19", "product_brand": "Blackmores", "nearest_outlet": "Alpro Petaling Jaya", "points_balance": "225", "total_spending": "725.74", "member_category": "Corporate", "membership_type": "Standard", "engagement_score": "25", "product_category": "Baby Care, Personal Care", "last_visit_outlet": "Alpro Petaling Jaya", "last_purchase_date": "2026-03-18", "preferred_language": "English", "purchase_frequency": "3", "client_interest_group": "Chronic care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-03-09 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat35@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00036', 'success+uat36@simulator.amazonses.com', 'Siti Rahman', '{"city": "Ipoh", "race": "Malay", "lofra": "Average", "state": "Perak", "gender": "M", "mobile": "0100000037", "dormant": "0", "birthday": "1984-12-03", "rfm_score": "11", "nationality": "Others", "rfm_segment": "Loyal", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1036", "create_outlet": "Alpro Kuching", "points_expiry": "2026-12-16", "product_brand": "Panadol", "nearest_outlet": "Alpro Online", "points_balance": "1480", "total_spending": "2146.00", "member_category": "Personal", "membership_type": "Gold", "engagement_score": "74", "product_category": "Medicine, Baby Care", "last_visit_outlet": "Alpro Online", "last_purchase_date": "2026-08-21", "preferred_language": "English", "purchase_frequency": "13", "client_interest_group": "Health supplements", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2025-08-19 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat36@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00037', 'success+uat37@simulator.amazonses.com', 'Zara Hassan', '{"city": "Melaka", "race": "Indian", "lofra": "Average", "state": "Melaka", "gender": "M", "mobile": "0100000038", "dormant": "0", "birthday": "1987-02-10", "rfm_score": "11", "nationality": "Malaysian", "rfm_segment": "Potential Loyalist", "group_outlet": "Alpro Johor Bahru", "voucher_code": "UAT-1037", "create_outlet": "Alpro Johor Bahru", "points_expiry": "2027-03-27", "product_brand": "Bio-Life", "nearest_outlet": "Alpro Ipoh", "points_balance": "1407", "total_spending": "1407.99", "member_category": "Personal", "membership_type": "Silver", "engagement_score": "67", "product_category": "Personal Care, Supplements", "last_visit_outlet": "Alpro Ipoh", "last_purchase_date": "2026-08-07", "preferred_language": "English", "purchase_frequency": "10", "client_interest_group": "Baby and mother care", "client_sales_category": "Staff"}', 'uat-seed', 1, '2024-11-06 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat37@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00038', 'success+uat38@simulator.amazonses.com', 'Farah Lim', '{"city": "Alor Setar", "race": "Indian", "lofra": "Hopper", "state": "Kedah", "gender": "F", "mobile": "0100000039", "dormant": "0", "birthday": "1951-11-08", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro George Town", "voucher_code": "UAT-1038", "create_outlet": "Alpro George Town", "points_expiry": "2027-03-04", "product_brand": "Cetaphil", "nearest_outlet": "Alpro Kota Kinabalu", "points_balance": "130", "total_spending": "325.19", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "13", "product_category": "Medicine", "last_visit_outlet": "Alpro Kota Kinabalu", "last_purchase_date": "2026-03-28", "preferred_language": "English", "purchase_frequency": "0", "client_interest_group": "Beauty and skincare", "client_sales_category": "Retail"}', 'uat-seed', 1, '2026-09-10 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat38@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00039', 'success+uat39@simulator.amazonses.com', 'Kevin Rahman', '{"city": "Sandakan", "race": "Malay", "lofra": "Risk", "state": "Sabah", "gender": "M", "mobile": "0100000040", "dormant": "1", "birthday": "1965-12-14", "rfm_score": "3", "nationality": "Malaysian", "rfm_segment": "Dormant", "group_outlet": "Alpro Kuching", "voucher_code": "UAT-1039", "create_outlet": "Alpro Kuching", "points_expiry": "2027-07-16", "product_brand": "Panadol", "nearest_outlet": "Alpro Klang", "points_balance": "230", "total_spending": "437.39", "member_category": "Personal", "membership_type": "Standard", "engagement_score": "23", "product_category": "Medical Devices, Beauty", "last_visit_outlet": "Alpro Klang", "last_purchase_date": "2025-09-18", "preferred_language": "English", "purchase_frequency": "4", "client_interest_group": "Elderly care", "client_sales_category": "Wholesale"}', 'uat-seed', 1, '2026-07-01 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat39@simulator.amazonses.com' AND `deleted_at` IS NULL);
INSERT INTO `edm_list_members` (`list_id`, `member_code`, `email`, `name`, `fields`, `source`, `status`, `subscribed_at`, `created_at`, `updated_at`)
SELECT @uat, 'UAT00040', 'success+uat40@simulator.amazonses.com', 'Jun Hao Rahman', '{"city": "Batu Pahat", "race": "Malay", "lofra": "Loyal", "state": "Johor", "gender": "F", "mobile": "0100000041", "dormant": "0", "birthday": "1996-12-18", "rfm_score": "13", "nationality": "Indonesian", "rfm_segment": "VIP", "group_outlet": "Alpro Petaling Jaya", "voucher_code": "UAT-1040", "create_outlet": "Alpro Petaling Jaya", "points_expiry": "2027-07-14", "product_brand": "Drypers", "nearest_outlet": "Alpro Ipoh", "points_balance": "819", "total_spending": "3640.23", "member_category": "Personal", "membership_type": "Platinum", "engagement_score": "91", "product_category": "Beauty, Medical Devices", "last_visit_outlet": "Alpro Ipoh", "last_purchase_date": "2026-09-04", "preferred_language": "Bahasa Malaysia", "purchase_frequency": "17", "client_interest_group": "Fitness", "client_sales_category": "Staff"}', 'uat-seed', 1, '2025-05-07 10:00:00', @now, @now FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `edm_list_members` WHERE `list_id` = @uat AND `email` = 'success+uat40@simulator.amazonses.com' AND `deleted_at` IS NULL);
